---
# Copy to inventory.yml (git-ignored)
all:
  hosts:
    oats-store:
      ansible_host: oats-vm.lan  # VM hostname or IP
      ansible_user: ubuntu       # SSH username (needs sudo)

      # Set the nginx vhost so the store is accessible via HTTP.
      oats_public_hostname: oats-store.opendronemap.org

      # Change if you want to store the data somewhere else.
      # oats_data_root: /var/lib/garage

      # Install nginx alongside garage if there is no external proxy.
      # oats_nginx_manage: true
